### ISSUE TITLE
Way to update easyp.lock

### ISSUE THREAD

**Issue by d-enk** [easyp-tech/easyp#54]
```yaml
#easyp.yaml
deps:
  - github.com/gogo/protobuf@v1.3.1
```

```sh
$ easyp mod download 
# INFO Install package package=github.com/gogo/protobuf version=v1.3.1 commit=5628607bb4c51c3157aacc3a50f0ab707582b805
```

```yaml
#easyp.yaml
deps:
  - github.com/gogo/protobuf@v1.3.2
```

```sh
$ easyp mod download 
# INFO Install package package=github.com/gogo/protobuf version=v1.3.1 commit=5628607bb4c51c3157aacc3a50f0ab707582b805
```

Something needs to change this behavior.
Additional flag maybe, like yarn `--immutable`

**Comment by hound672** [comment]
Hello. For now easyp reads version from lock file and ignore version from easyp.yaml.
@ZergsLaw what do you think?

My suggestion:
1. Read version from easyp.yaml -> if it's absent install version from lock file
1.2. if version is absent in lock file -> install the latest

2. If version in easyp.yaml is higher than in lock file -> install new version and update lock file

**Comment by ZergsLaw** [comment]
Mb we can just add new command? For example

```sh
easyp mod update
```

And this commang can use versions from easyp.yml?

**Comment by d-enk** [comment]
> Mb we can just add new command? For example
> 
> ```shell
> easyp mod update
I think so

And error for download when version differently

**Comment by hound672** [comment]
So, by default for `easyp mod download` use versions from lock file and ignore versions from easyp.yaml
For `easyp mod update` read versions from easyp.yaml and update lock file
right?

**Comment by ZergsLaw** [comment]
My opinion - yes

**Comment by d-enk** [comment]
`go mod download` with a new version in go.mod just updates go.sum
