### ISSUE TITLE
[BUG] Incorrect validation of message names and field names

### ISSUE THREAD

**Issue by esqp** [easyp-tech/easyp#80]
When validating message names containing numbers, the error `message is not pascal case` is thrown.

Examples:
```
message S3Data {
  ...
}

message InfoS3 {
  ...
}
``` 

When validating message fields names containing numbers, the error `message field is not lower snake case` is thrown.

Examples:
```
message Info {
  string s3_bucket = 1;
  string s3_path = 2;
}
```

**Comment by hound672** [comment]
Close? Since PR was merged
