### ISSUE TITLE
[BUG] got   import is not used (IMPORT_USED) error when extending import package

### ISSUE THREAD

**Issue by arykalin** [easyp-tech/easyp#94]
Describe the bug
When import used for extend got   import is not used error

To Reproduce
1. Create proto which extends MethodOoptions filed:
```
syntax = "proto3";
package rbac.v1;

import "google/protobuf/descriptor.proto";

extend google.protobuf.MethodOptions {
  MethodOption options = 10000;
}


message MethodOption {}

```
2. Pass the argument: `easyp lint --path options.proto
3. Observe the error

Expected behavior
No error

Log files
If applicable, add log files to help explain your problem.

Desktop (please complete the following information):
 - OS: Ubuntu 22.04 LTS
 - CLI Tool version: easyp version v0.6.3
 - Proto Compiler version: v5.28.2

**Comment by hound672** [comment]
Please try fix: 
```
go install github.com/easyp-tech/easyp/cmd/easyp@v0.6.4-rc1
```

**Comment by arykalin** [comment]
> Please try fix:
> 
> ```
> go install github.com/easyp-tech/easyp/cmd/easyp@v0.6.4-rc1
> ```

Yes, it works, thank you!
